/* Aufgaben für EF, Q1 und Q2. Aufgabentypen wechseln bewusst zwischen Rechnen,
   Darstellungswechsel, Modellierung und Fehlerdiagnose. */
window.G=window.G||{};var G=window.G;
G.transform=(k,d,r,v)=>{let a=r(1,3),h=r(-2,2),j=r(-2,2);
 if(k===0)return C(`Welche Wirkung hat f(x)=g(x−${a})?`,'Verschiebung des Graphen um '+a+' nach rechts.',['Verschiebung um '+a+' nach links.','Streckung in y-Richtung mit Faktor '+a+'.'],'Ein inneres x−a wird durch x=a null; der Graph von g wird nach rechts verschoben.',H('Betrachte die Stelle, an der die Klammer null wird.','Innen und außen wirken verschieden.','x−a=0 bei x=a.'));
 if(k===1)return N(`Der Graph von g hat den Scheitel (0|0). Bestimme den Scheitel von f(x)=${a}·g(x)+${j}.`,[0,j],`Der Faktor ${a} streckt in y-Richtung; +${j} verschiebt vertikal. Der Scheitel ist (0|${j}).`,H('Ein Außenfaktor verändert y-Werte.','Die x-Koordinate bleibt hier gleich.','Addiere '+j+' zur y-Koordinate.'),{labels:['x','y']});
 if(k===2)return L('Verändere a, h und k so, dass die Zielparabel f(x)=a(x−h)²+k entsteht.','parabola',[a,h,j],`Die drei Parameter sind direkt ablesbar: a=${a}, h=${h}, k=${j}.`,H('Der Scheitel liefert h und k.','Prüfe anschließend die Öffnung.','Ein Punkt neben dem Scheitel liefert a.'),{predict:['h verschiebt horizontal.','k verschiebt vertikal.'],reason:'In a(x−h)²+k steuern die Parameter Streckung, horizontale und vertikale Lage.',reasons:['In a(x−h)²+k steuern die Parameter Streckung, horizontale und vertikale Lage.','Alle Parameter verschieben nur horizontal.']});
 return C('Welche Aussage muss bei einer Funktion mit Definitionslücke zusätzlich geprüft werden?','Ob die Transformation den Definitionsbereich korrekt mitnimmt.',['Nur der y-Achsenabschnitt.','Nur die Farbe des Graphen.'],'Eine Verschiebung oder Spiegelung verändert auch die ausgeschlossenen x-Werte. Der Definitionsbereich gehört zur Funktionsbeschreibung.',H('Transformationen wirken auf x- und y-Werte.','Frage nach verbotenen Eingaben.','Ein Loch im Graphen wandert mit.'));
};

G.ableitung=(k,d,r,v)=>{let a=r(2,5+d),x=r(-2,2);
 if(k===0)return N(`Für f(x)=x² ist die Sekantensteigung zwischen x=0 und x=${a} gleich ?`,a,`m=(f(${a})−f(0))/(${a}−0)=${a*a}/${a}=${a}.`,H('Sekantensteigung = Δy/Δx.','Berechne zuerst die beiden Funktionswerte.','f('+a+')='+a*a+'.'),{visual:plot([{fn:x=>x*x}],[0,a+1,-1,a*a+2],[[0,0],[a,a*a]]),rep:'graphisch'});
 if(k===1)return N(`Für f(x)=x²: Welche Tangentensteigung hat der Graph bei x=${a}?`,2*a,`f′(x)=2x. Also f′(${a})=${2*a}.`,H('Die Ableitung gibt die lokale Steigung.','Leite x² ab.',`Setze x=${a} in 2x ein.`),{visual:plot([{fn:x=>x*x}],[a-2,a+2,-1,(a+2)**2+1],[[a,a*a,'T']]),rep:'graphisch'});
 if(k===2)return C(`An einer Stelle gilt f′(x)=0. Welche Aussage ist sicher?`,'Die Tangente ist waagerecht.',['Es liegt sicher ein Hochpunkt vor.','Der Funktionswert ist null.'],'f′=0 ist eine notwendige Bedingung für innere Extremstellen, aber auch bei einem Sattelpunkt möglich.',H('f′ beschreibt die Steigung, nicht den Funktionswert.','Eine waagerechte Tangente kann verschiedene Formen haben.','Für ein Extremum braucht man zusätzlich einen Vorzeichenwechsel oder ein hinreichendes Kriterium.'));
 return L('Bewege die Sekante so, dass sie die Tangente bei x=1 möglichst gut annähert.','secant',[0.05],`Im Grenzübergang wird aus der Sekantensteigung die lokale Änderungsrate f′(1). Ein kleiner Abstand von 0,05 ist hier eine gute Näherung.`,H('Verkleinere den Abstand der beiden x-Werte.','Beobachte die Steigung.','Sekante und Tangente stimmen im Grenzfall überein.'),{predict:['Die Sekante nähert sich der Tangente.','Die Steigung wird immer null.'],reason:'Der Differenzenquotient geht beim Grenzübergang in den Differentialquotienten über.',reasons:['Der Differenzenquotient geht beim Grenzübergang in den Differentialquotienten über.','Der y-Wert wird zum x-Wert.']});
};

G.kurven=(k,d,r,v)=>{let a=r(1,4),b=r(2,5);
 if(k===0)return C(`Eine Funktion hat f′(x)>0 in einem Intervall. Wie verläuft f dort?`,'f ist streng monoton steigend.',['f ist dort konstant.','f hat dort zwingend ein Maximum.'],'Positive lokale Änderungsraten bedeuten, dass f wächst.',H('f′ ist die Steigung.','Positive Steigung zeigt nach oben.','„Zwingend Maximum“ wäre eine zusätzliche Aussage.'));
 if(k===1)return C('f′ wechselt an x=2 von positiv zu negativ. Was liegt dort vor?','Ein lokales Maximum.', ['Ein lokales Minimum.','Eine sichere Wendestelle.'],'Vorher steigt f, nachher fällt f: Das ist ein lokales Maximum.',H('Lies die Vorzeichen links und rechts.','Steigen zu Fallen bedeutet Gipfel.','Ein Minimum wäre der Wechsel − zu +.'));
 if(k===2)return N(`f(x)=x³−${a}x. Bestimme f′(0).`, -a, `f′(x)=3x²−${a}. Daher f′(0)=−${a}.`,H('Leite jeden Summanden ab.','Die Ableitung von −ax ist −a.',`3·0²−${a}=−${a}.`));
 return C('Warum müssen bei einer globalen Extremwertfrage auch Randwerte geprüft werden?','Ein inneres Extremum kann am Rand nicht alle möglichen Vergleichswerte übertreffen.',['Randwerte sind immer Ableitungsnullstellen.','Randwerte sind mathematisch bedeutungslos.'],'Auf einem abgeschlossenen Intervall kann das größte oder kleinste Ergebnis am Rand liegen, auch wenn f′ dort nicht null ist.',H('Global bedeutet im ganzen Definitionsintervall.','Vergleiche alle Kandidaten.','Der Rand gehört zum Intervall.'));
};

G.vektor=(k,d,r,v)=>{let a=r(2,5),b=r(1,4);
 if(k===0)return N(`A(${a}|${b}|0), B(0|${b}|${a}). Bestimme den Verbindungsvektor AB.`,[-a,0,a],`AB=B−A=(${fmt(-a)}|0|${a}).`,H('Endpunkt minus Startpunkt.','Subtrahiere die Koordinaten einzeln.',`0−${a}=${-a}; ${b}−${b}=0.`),{labels:['x','y','z'],rep:'vektoriell'});
 if(k===1)return N(`Bestimme die Länge von v=(${a}|${a}|${b}).`,Math.sqrt(2*a*a+b*b),`|v|=√(${a}²+${a}²+${b}²)=√${2*a*a+b*b}≈${fmt(Math.sqrt(2*a*a+b*b),2)}.`,H('Die Vektorlänge ist die 3D-Diagonale.','Quadriere alle Komponenten und addiere.',`Unter der Wurzel steht ${2*a*a+b*b}.`),{tolerance:.006});
 if(k===2)return C(`Sind u=(${a}|${b}|0) und v=(${2*a}|${2*b}|0) kollinear?`,'Ja, v=2u.',['Nein, weil die Koordinaten verschieden sind.','Nur Nullvektoren können kollinear sein.'],'Alle Komponenten von v sind mit demselben Faktor 2 aus u entstanden.',H('Kollinearität bedeutet Vielfachheit.','Prüfe x, y und z mit demselben Faktor.','2a/a=2 und 2b/b=2.'));
 return N(`Eine Drohne startet bei A(1|2|0) und fliegt mit v=(${a}|0|${b}) für t=3. Bestimme den Endpunkt.`,[1+3*a,2,3*b],`X(3)=A+3v=(1+3·${a}|2|3·${b})=(${1+3*a}|2|${3*b}).`,H('Der Parameter gibt die Anzahl der Vektorschritte an.','Multipliziere v mit 3.',`x=1+3·${a}.`),{labels:['x','y','z'],rep:'kontextuell'});
};

G.geraden=(k,d,r,v)=>{let a=r(1,4),b=r(1,4),c=r(1,4);
 if(k===0)return C(`g: X=(0|0|0)+t·(1|${a}|0), h: X=(1|${a}|2)+s·(2|${2*a}|0). Welche Lage ist sicher?`,'parallel.', ['identisch.','windschief.'],'Die Richtungsvektoren sind Vielfache; die Stützpunkte liegen aber nicht auf derselben Geraden.',H('Vergleiche zuerst die Richtungsvektoren.','Eine Punktprobe entscheidet identisch oder echt parallel.','Der z-Abstand 2 verhindert Identität.'));
 if(k===1)return N('g: X=(1|0|0)+t·(1|1|0), h: X=(0|1|0)+s·(−1|1|0). Bestimme den Schnittpunkt.',[1,0,0],`Aus y: t=1+s und aus x: 1+t=−s folgt s=−1, t=0. Der Schnittpunkt ist g(0)=(1|0|0).`,H('Setze die drei Koordinatengleichungen gleich.','Aus y folgt t=1+s.','Setze das in die x-Gleichung ein und löse nach s.'),{labels:['x','y','z'],rep:'vektoriell'});
 if(k===2)return C('Was bedeutet eine eindeutige Lösung des LGS beim Geradenschnitt?','Die Geraden schneiden sich genau in einem Punkt.',['Die Geraden sind identisch.','Die Geraden sind parallel ohne Schnitt.'],'Ein eindeutiges Parameterpaar liefert genau einen gemeinsamen Punkt.',H('Jede Lösung entspricht einem gemeinsamen Parameterpaar.','Eine Lösung ist ein Punkt.','Keine Lösung bedeutet nicht schneiden.'));
 return E('Prüfe den Lagecheck. Die erste Zeile ist fehlerhaft.',['Richtungsvektoren vergleichen','Wenn kein Vielfaches: LGS aufstellen','Schnittpunkt durch Einsetzen prüfen'],0,1,'„Nicht parallel“ reicht im Raum nicht als Schnittnachweis.',['Ein Raumproblem hat immer einen Schnittpunkt.','Die Richtungsvektoren müssen immer gleich sein.'],`Zuerst wird auf Vielfachheit geprüft; danach entscheidet das LGS zwischen Schnitt und windschief.`,H('In 3D können Geraden windschief sein.','Nicht parallel ist nur ein Zwischenergebnis.','Das LGS muss lösbar sein.'));
};

G.bruecke=(k,d,r,v)=>{let a=r(2,5),b=r(2,5);
 if(k===0)return N(`Eine faire Münze wird zweimal geworfen. P(genau einmal Kopf)=?`,.5,`Die Pfade KZ und ZK sind disjunkt: 1/4+1/4=1/2.`,H('Zeichne zwei Stufen.','Genau einmal hat zwei Reihenfolgen.','Jeder Pfad hat Wahrscheinlichkeit 1/4.'),{tolerance:.001,visual:tree(1,1),rep:'graphisch'});
 if(k===1)return N(`Eine Vierfeldertafel enthält A∩B=${a}/100, A=${(a+b)}/100. Bestimme P(B|A).`,a/(a+b),`P(B|A)=P(A∩B)/P(A)=${a}/${a+b}=${fmt(a/(a+b),3)}.`,H('Die Bedingung A ist der Bezugsraum.','Teile den Schnitt durch A.',`Nenner ${a+b}.`),{tolerance:.001,visual:four(a,b,18,100-a-b-18),rep:'tabellarisch'});
 if(k===2)return C('Wann darf ein Bernoulli-/Binomialmodell verwendet werden?','Feste Anzahl unabhängiger Versuche mit gleicher Trefferwahrscheinlichkeit p.',['Die Trefferwahrscheinlichkeit ändert sich nach jedem Versuch.','Jede Zufallsgröße ist automatisch binomialverteilt.'],'Unabhängigkeit, konstantes p und genau zwei Ausgänge pro Versuch sind nötig.',H('Prüfe die Modellannahmen einzeln.','Ohne Zurücklegen ändert sich p meist.','„Genau zwei Ausgänge“ ist eine Vereinfachung der Betrachtung.'));
 return C('„P(A und B)“ und „P(A|B)“ sind gleich. Wann stimmt das?','Nur wenn P(A|B)=P(A) bzw. A und B unabhängig sind.',['Immer, weil beide A enthalten.','Nur bei disjunkten Ereignissen.'],'Die bedingte Wahrscheinlichkeit berücksichtigt den veränderten Bezugsraum; Gleichheit ist ein Unabhängigkeitskriterium.',H('Der senkrechte Strich bedeutet „unter der Bedingung“.','Vergleiche die Bezugsräume.','Unabhängigkeit lässt den Bezugsraum wirkungslos werden.'));
};

G.produkt=(k,d,r,v)=>{let a=r(2,4),b=r(1,3);
 if(k===0)return C(`Für f(x)=(x²+${a})·e^x: Welche Faktoren sind u und v?`,`u=x²+${a} und v=e^x`,[`u=x² und v=${a}·e^x.`,`u=e^x und v=x²+${a}.`],'Die Faktoren dürfen grundsätzlich gewählt werden; diese Wahl hält aber die Produktstruktur und Ableitungen übersichtlich.',H('Trenne die beiden Faktoren durch den Malpunkt.','Ein Summand gehört vollständig zu einem Faktor.','e^x ist der zweite Faktor.'));
 if(k===1)return O('Ordne die Produktregel-Schritte.',["u und v festlegen.","u′ und v′ bestimmen.","f′=u′·v+u·v′ einsetzen.","Ergebnis zusammenfassen."],'Die Faktoren werden zuerst identifiziert; danach werden beide einzeln abgeleitet und in die Regel eingesetzt.',H('Eine Regel braucht zunächst ihre Bausteine.','Leite erst u und v ab.','Die beiden Summanden der Regel müssen beide erscheinen.'));
 if(k===2)return N(`Leite f(x)=x·e^(${b}x) ab und berechne f′(0).`,1,`f′=1·e^(${b}x)+x·${b}e^(${b}x). Für x=0 bleibt 1.`,H('u=x, v=e^('+b+'x).','Verwende die Produktregel und die Kettenregel.',`e^0=1; der Term mit x verschwindet.`));
 return E('Finde die falsche Produktregel und gib den fehlenden Term an.',[`u=x²`, `v=e^x`, `f′=2x·e^x`],1,`x²·e^x`,'Der Term u·v′ fehlt.',['u′v allein reicht bei einem Produkt nicht.','Die Regel lautet u′v′.'],`f′=2x·e^x+x²·e^x. Der fehlende Term ist x²·e^x.`,H('Die Produktregel hat zwei Summanden.','Der zweite entsteht aus u·v′.','v′=e^x.'));
};

G.exp=(k,d,r,v)=>{let a=r(2,5),b=r(1,3);
 if(k===0)return N(`Leite f(x)=e^(${a}x) ab und gib f′(0) an.`,a,`f′(x)=${a}e^(${a}x), daher f′(0)=${a}.`,H('Bei e^u wird mit der inneren Ableitung multipliziert.','Die innere Funktion ist '+a+'x.','e^0=1.'));
 if(k===1)return N(`Ein Bestand B(t)=${a}·e^(−${b}t) startet bei t=0. Wie groß ist die momentane Änderungsrate bei t=0?`,-a*b,`B′(t)=−${a*b}e^(−${b}t), also B′(0)=−${a*b}. Das Minus zeigt Abnahme.`,H('Leite den Exponenten mit ab.','Setze t=0 ein.',`−${a}·${b}·1=−${a*b}.`),{unit:'Einheiten pro Zeit',rep:'kontextuell'});
 if(k===2)return C('Was beschreibt bei B(t)=B₀e^(kt) der Parameter k?','Die relative Änderungsrate pro Zeiteinheit.',['Den Anfangsbestand B₀.','Die absolute Änderung unabhängig vom Bestand.'],'Für kleine Zeitschritte ist B′/B=k. Das Vorzeichen entscheidet über Wachstum oder Zerfall.',H('Vergleiche B′ mit B.','B₀ steht für den Anfang.','k multipliziert den aktuellen Bestand.'));
 return C('Ein logistischer Wachstumsprozess wird durch eine reine Exponentialfunktion beschrieben. Welche Kritik ist sinnvoll?','Die Sättigungsgrenze fehlt im Modell.',['Exponentielles Wachstum ist immer falsch.','Die Daten dürfen nicht verwendet werden.'],'Exponentielles Wachstum kann in einer frühen Phase passen, überschätzt aber ohne Begrenzung oft langfristig den Bestand.',H('Prüfe die Langzeitprognose.','Ressourcen können begrenzen.','Ein Modell kann für einen Zeitraum trotzdem nützlich sein.'));
};

G.integral=(k,d,r,v)=>{let a=r(2,5),b=r(1,4);
 if(k===0)return N(`Eine konstante Änderungsrate von ${a} L/min wirkt ${b} min. Wie viel Bestand kommt hinzu?`,a*b,`Änderung = Rate · Zeit = ${a}·${b}=${a*b} L.`,H('Bei konstanter Rate ist die Fläche ein Rechteck.','Fläche unter dem Rate-Graphen.',`${a} · ${b}.`),{unit:'L',rep:'kontextuell',visual:plot([{fn:x=>a}],[0,b,0,a+1])});
 if(k===1)return N(`Bestimme ∫₀^${a} 2x dx.`,a*a,`Eine Stammfunktion ist x². [x²]₀^${a}=${a*a}.`,H('Suche eine Stammfunktion.','Die Ableitung von x² ist 2x.',`Setze obere minus untere Grenze ein.`));
 if(k===2)return C('Was bedeutet ein negatives bestimmtes Integral im Kontext eines Tankmodells?','Im betrachteten Intervall überwiegt Abfluss gegenüber Zufluss.',['Der Tankinhalt ist negativ.','Es gibt überhaupt keinen Bestand.'],'Das Integral der Änderungsrate gibt die Bestandsänderung an; ein negatives Ergebnis bedeutet Abnahme.',H('Integriert wird eine Rate.','Rate und Bestand sind verschiedene Größen.','Negativ beschreibt die Richtung der Änderung.'));
 return L('Vergleiche Produktsumme und Integral: Verkleinere die Rechteckbreite.','riemann',[a],`Mit immer feineren Rechtecken nähert sich die Produktsumme dem Integral an.`,H('Teile die Fläche in gleich breite Streifen.','Verkleinere Δx.','Die Summe der Rechtecke wird genauer.'),{predict:['Die Näherung wird genauer.','Die Rechtecke verschwinden sofort vollständig.'],reason:'Das Integral ist der Grenzwert der Produktsummen.',reasons:['Das Integral ist der Grenzwert der Produktsummen.','Das Integral ist stets die erste Rechtecksumme.']});
};

G.skalar=(k,d,r,v)=>{let a=r(1,4),b=r(1,4);
 if(k===0)return N(`Berechne u·v für u=(${a}|${b}|0), v=(${b}|−${a}|0).`,0,`${a}·${b}+${b}·(−${a})=0. Die Vektoren sind orthogonal.`,H('Multipliziere entsprechende Komponenten.','Addiere die Produkte.',`Die beiden Produkte heben sich auf.`),{rep:'vektoriell'});
 if(k===1)return C('Was bedeutet u·v=0 geometrisch (für Nichtnullvektoren)?','u und v stehen senkrecht aufeinander.',['u und v sind gleich.','u und v sind parallel.'],'Das Skalarprodukt Null kennzeichnet Orthogonalität.',H('Das Skalarprodukt misst den Richtungsanteil.','Null bedeutet kein Anteil in der Richtung des anderen.','Der Fachbegriff ist Orthogonalität.'));
 if(k===2)return N(`u=(${a}|0|0), v=(0|${b}|0). Gib cos(α) an.`,0,`u·v=0, also cos(α)=0/(|u||v|)=0; α=90°.`,H('Berechne das Skalarprodukt.','Die Vektoren liegen auf zwei Koordinatenachsen.','Nenner ist ungleich null.'));
 return C('Beim Winkel zwischen einer Geraden und einer Ebene wird der Winkel zum Normalenvektor verwendet. Was muss danach geschehen?','Den Ergänzungswinkel zu 90° berücksichtigen.',['Den Winkel verdoppeln.','Den Winkel unverändert als Ebenenwinkel ausgeben.'],'Der Winkel zwischen Gerade und Ebene ist der Komplementwinkel zum Winkel zwischen Gerade und Ebenennormale.',H('Normale und Ebene stehen senkrecht.','Skalarprodukt liefert zunächst den Normalenwinkel.','Ebene und Normale ergänzen sich zu 90°.'));
};

G.ebenen=(k,d,r,v)=>{let a=r(2,5),b=r(1,4);
 if(k===0)return C(`Liegt P(1|1|${a+b}) in E: ${a}x+${b}y−z=0?`,'Ja.',['Nein.','Nur wenn x=y.'],`Einsetzen: ${a}·1+${b}·1−(${a+b})=0. Damit erfüllt P die Ebenengleichung.`,H('Setze die Koordinaten in die linke Seite ein.','Eine Punktprobe verlangt genau 0.','Prüfe jede Variable mit ihrem Koeffizienten.'),{rep:'symbolisch'});
 if(k===1)return N(`E: ${a}x+${b}y+z=${a+b}. Welchen Normalenvektor hat E?`,[a,b,1],`Die Koeffizienten von x,y,z bilden einen Normalenvektor: n=(${a}|${b}|1).`,H('Lies die Koordinatenform ab.','Vor x, y und z stehen die Komponenten.','Die rechte Seite gehört nicht zum Normalenvektor.'),{labels:['n₁','n₂','n₃'],rep:'vektoriell'});
 if(k===2)return N(`g: X=(0|0|0)+t·(1|0|1), E: z=${a}. Bestimme den Parameter des Schnittpunkts.`,a,`Auf g gilt z=t. In E muss z=${a} sein, also t=${a}.`,H('Setze die Geradengleichung in die Ebenenbedingung ein.','Die z-Koordinate von g ist t.',`t=${a}.`),{rep:'vektoriell'});
 return C('Warum kann ein LGS bei einer Geraden-Ebene-Untersuchung unendlich viele Lösungen haben?','Die Gerade liegt vollständig in der Ebene.',['Die Gerade hat keine Punkte.','Die Ebene ist dann ein Punkt.'],'Jeder Parameterwert der Geraden erfüllt dann die Ebenengleichung.',H('Jede Lösung ist ein Punkt der Geraden.','Unendlich viele Parameter bedeuten unendlich viele gemeinsame Punkte.','Das beschreibt die Lage „Gerade in Ebene“.'),{rep:'sprachlich'});
};

G.binomial=(k,d,r,v)=>{let n=5+r(0,3),p=[.2,.4,.6][r(0,2)],kk=2;
 if(k===0)return C(`Ein Bernoulli-Versuch hat p=${p}. Ist X=Anzahl der Treffer in n=${n} Versuchen binomialverteilt?`,'Ja, wenn die Versuche unabhängig und p konstant sind.',['Nein, weil X ganzzahlig ist.','Ja, unabhängig von der Versuchszahl.'],'Die Bedingungen sind feste Versuchszahl, Unabhängigkeit, konstantes p und zwei Ausgänge.',H('Prüfe alle vier Modellkriterien.','X zählt Treffer.','Die Versuchszahl n ist fest.'));
 if(k===1)return N(`Berechne P(X=${kk}) für X~B(${n};${p}).`,bp(n,p,kk),`P(X=${kk})=C(${n},${kk})·${p}^${kk}·${fmt(1-p)}^${n-kk}≈${fmt(bp(n,p,kk),4)}.`,H('Verwende die Binomialformel.','Der Binomialkoeffizient zählt die möglichen Reihenfolgen.',`Setze n=${n}, p=${p}, k=${kk} ein.`),{tolerance:.0006,rep:'symbolisch'});
 if(k===2)return N(`Für X~B(${n};${p}) gilt μ=n·p. Bestimme den Erwartungswert.`,n*p,`μ=${n}·${p}=${n*p}. Das ist ein Mittelwert vieler gleichartiger Serien, keine Garantie für eine einzelne Serie.`,H('Erwartungswert = Versuchszahl · Trefferwahrscheinlichkeit.','Multipliziere n und p.',`n=${n}, p=${p}.`),{rep:'kontextuell'});
 return C('Wie verändert sich ein Histogramm bei größerem n und gleichem p?','Die Verteilung liegt bei größerem Erwartungswert und wird relativ konzentrierter.',['Der Erwartungswert bleibt gleich.','Jede Säule wird automatisch doppelt so hoch.'],'μ=np wächst mit n; die relative Streuung nimmt typischerweise ab, während die absolute Streuung √(np(1−p)) wächst.',H('Vergleiche μ und σ getrennt.','n wirkt auf beide Kenngrößen.','Ein Histogramm zeigt Wahrscheinlichkeiten, nicht nur Rohzahlen.'),{rep:'graphisch'});
};

G.erwartung=(k,d,r,v)=>{let a=r(1,3),b=r(3,6);
 if(k===0)return N(`Ein Spiel zahlt mit P=0,5 den Gewinn ${b} € und sonst 0 €. Bestimme den Erwartungswert.`,b/2,`E(X)=0,5·${b}+0,5·0=${fmt(b/2)} €.`,H('Gewinne werden mit ihren Wahrscheinlichkeiten gewichtet.','Es gibt zwei Ausgänge.','Die Hälfte von '+b+' ist '+fmt(b/2)+'.'),{unit:'€',rep:'kontextuell'});
 if(k===1)return C(`Ein Einsatz kostet ${a} €. Der Erwartungswert der Auszahlung beträgt ${b} €. Ist das Spiel fair?`,'Nein, der erwartete Nettogewinn ist '+fmt(b-a)+' €.',[`Ja, jeder einzelne Ausgang ist fair.`,`Ja, weil der Erwartungswert immer der Einsatz ist.`],`Fair wäre E(Auszahlung)−Einsatz=0. Hier ergibt sich ${b}−${a}=${b-a} €; das Spiel ist nur dann fair, wenn dieser Wert null wäre.`,H('Vergleiche Auszahlung und Einsatz.','Fair bezieht sich auf den erwarteten Nettogewinn.','Ziehe den Einsatz ab.'),{rep:'kontextuell'});
 if(k===2)return N('Eine Zufallsgröße hat die Werte 0, 1 und 2 mit Wahrscheinlichkeiten 0,25; 0,5; 0,25. Bestimme E(X).',1,'E(X)=0·0,25+1·0,5+2·0,25=1.',H('Multipliziere jeden Wert mit seiner Wahrscheinlichkeit.','Addiere die drei Beiträge.','Die Randwerte tragen jeweils 0,5 bei.'));
 return C('Was beschreibt die Varianz?','Die mittlere quadrierte Abweichung vom Erwartungswert.',['Die Summe aller Werte.','Die größte mögliche Auszahlung.'],'Die Varianz misst die Streuung um den Erwartungswert; durch das Quadrieren verschwinden Vorzeichen.',H('Streuung ist nicht Lage.','Abweichungen können positiv und negativ sein.','Quadrate machen alle Beiträge nichtnegativ.'));
};

G.abi_analysis=(k,d,r,v)=>{let a=r(2,4),b=r(1,3);
 if(k===0)return N(`Ein Tank hat Änderungsrate r(t)=${a}t−${b} L/min. Bestimme r(0).`, -b, `r(0)=${a}·0−${b}=−${b} L/min. Zu Beginn nimmt der Bestand ab.`,H('Setze t=0 ein.','Die Rate ist nicht der Bestand.','Das Minus zeigt Abfluss.'));
 if(k===1)return N(`Der Bestand ist B(t)=t³−${a}t²+${b}t+20. Bestimme B′(1).`,3-2*a+b,`B′(t)=3t²−${2*a}t+${b}; B′(1)=${3-2*a+b}.`,H('Leite B termweise ab.','Setze erst danach t=1 ein.',`3−${2*a}+${b}.`));
 if(k===2)return C('Ein Modell passt in den Messdaten gut, liefert aber für t<0 negative Zeiten. Wie ist das Ergebnis zu beurteilen?','Der Definitionsbereich muss auf sinnvolle Zeiten eingeschränkt werden.',['Das Modell ist deshalb vollständig falsch.','Negative Zeiten werden als zusätzliche Messdaten verwendet.'],'Mathematische Funktionen können größer definiert sein als der Sachkontext. Interpretation verlangt eine passende Einschränkung.',H('Prüfe die Bedeutung von t.','Nicht jeder rechnerisch mögliche Wert ist sachlich erlaubt.','Grenze den Modellbereich ein.'),{operator:'beurteilen',rep:'kontextuell'});
 return O('Ordne eine abiturähnliche Analysis-Bearbeitung.', ['Änderungsrate und Größen im Kontext identifizieren.','Ableitung/Integral passend auswählen und rechnen.','Ergebnis mit Einheit und Bezug deuten.','Modellannahme oder Gültigkeitsbereich beurteilen.'],'Erst wird der Kontext mathematisiert, dann gerechnet, anschließend interpretiert und kritisch beurteilt.',H('Beginne nicht mit einer Formel ohne Größenbedeutung.','Die Rechnung braucht eine Deutung.','Am Ende steht die Modellkritik.'));
};

G.steckbrief=(k,d,r,v)=>{let a=r(2,4);
 if(k===0)return C('Welche Information liefert f′(x₀)=0 in einer Steckbriefaufgabe?','Eine waagerechte Tangente bei x₀.',['Den Funktionswert f(x₀)=0.','Eine Nullstelle von f′ ist immer ein Wendepunkt.'],'Die Bedingung f′(x₀)=0 liefert eine Gleichung für unbekannte Parameter; sie sagt zunächst nur „stationäre Stelle“.',H('f′ ist die Steigung.','f′=0 bedeutet waagerechte Tangente.','Für einen Extrempunkt braucht man mehr.'));
 if(k===1)return N(`f(x)=ax²+${a}x+1 hat bei x=1 eine waagerechte Tangente. Bestimme a.`,-a/2,`f′(x)=2ax+${a}. Bei x=1: 2a+${a}=0 ⇒ a=−${a/2}.`,H('Bilde die Ableitung.','Setze x=1 und f′=0 ein.','Löse die lineare Gleichung in a.'),{tolerance:.001});
 if(k===2)return C('Bei einem Optimierungsproblem mit Intervall [0,10] wurden innere kritische Stellen gefunden. Was fehlt vor dem globalen Urteil?','Die Randwerte und alle zulässigen Kandidaten vergleichen.',['Nur der größte innere Wert.','Die Nebenbedingung ignorieren.'],'Globale Extrema auf einem abgeschlossenen Intervall können an inneren kritischen Stellen oder am Rand liegen.',H('Global heißt gesamtes Intervall.','Prüfe x=0 und x=10.','Vergleiche danach die Funktionswerte.'));
 return O('Ordne die Modellierung eines Rechteck-Optimierungsproblems.', ['Variablen und Nebenbedingung festlegen.','Zielfunktion in einer Variablen aufstellen.','Definitionsbereich aus dem Kontext bestimmen.','Kritische Stellen und Randwerte vergleichen.'],'Die Nebenbedingung reduziert die Variablenzahl; der Kontext liefert den zulässigen Bereich und das globale Urteil.',H('Beginne mit den Größen.','Nutze die Nebenbedingung zum Einsetzen.','Ohne Definitionsbereich ist das Optimum nicht vollständig gesichert.'));
};

G.abi_raum=(k,d,r,v)=>{let a=r(2,4),b=r(1,3);
 if(k===0)return N(`Eine Landebahn liegt in E: z=${a}. Ein Flugweg ist g: X=(1|0|0)+t·(0|${b}|1). Bestimme den Durchstoßparameter.`,a,`Auf g ist z=t. Für E gilt t=${a}.`,H('Vergleiche die z-Koordinate.','Setze die Ebenengleichung ein.','z=t.'));
 if(k===1)return C('Ein berechneter Schnittpunkt liegt außerhalb des für den Flug zugelassenen Parameterintervalls [0,1]. Was bedeutet das?','Die unendliche Gerade schneidet die Ebene, aber der reale Flugabschnitt nicht.',['Der Schnittpunkt ist automatisch falsch.','Die Ebene existiert dort nicht.'],'Parametergerade und realer Abschnitt sind zu unterscheiden; der Kontext schränkt t ein.',H('Prüfe den Parameterbereich.','Eine Gerade ist unendlich.','Ein Flugweg kann nur ein Teilstück sein.'),{rep:'kontextuell'});
 if(k===2)return N(`g₁ und g₂ schneiden sich bei S(2|${a}|${b}). Wie viele gemeinsame Punkte haben sie?`,1,'Zwei Geraden mit genau einem gemeinsamen Punkt schneiden sich in genau diesem Punkt.',H('Ein Punkt ist die geometrische Bedeutung einer eindeutigen LGS-Lösung.','S ist bereits gegeben.','Nicht die Koordinatensumme ist gesucht.'));
 return O('Ordne eine Raum-Modellierung.', ['Situation in Punkte, Vektoren und Parameter übersetzen.','Lagebeziehung durch Richtungen und LGS untersuchen.','Geometrisches Ergebnis im Kontext prüfen.','Parameterbereich und Einheiten nennen.'],'Ein algebraischer Schnitt ist erst nach Kontextprüfung eine gültige Aussage über die reale Situation.',H('Die Modellierung kommt vor dem Rechnen.','LGS und Geometrie müssen verbunden werden.','Der Parameterbereich ist Teil der Interpretation.'));
};

G.abi_sto=(k,d,r,v)=>{let a=r(2,4),p=.7;
 if(k===0)return N(`Ein Test erkennt einen Fehler mit P(T|F)=${p}. Von 100 fehlerhaften Teilen: Wie viele werden im Mittel erkannt?`,70,`E(X)=100·${p}=70. Das ist ein Erwartungswert, keine Garantie.`,H('Trefferzahl = n·p.','Setze n=100 ein.','100 · 0,7 = 70.'),{rep:'kontextuell'});
 if(k===1)return N(`Bei X~B(10;0,5) bestimme P(X≥${a}) auf vier Dezimalstellen.`,Array.from({length:11-a},(_,i)=>bp(10,.5,a+i)).reduce((u,x)=>u+x,0),`P(X≥${a})=1−P(X≤${a-1})≈${fmt(Array.from({length:11-a},(_,i)=>bp(10,.5,a+i)).reduce((u,x)=>u+x,0),4)}.`,H('„Mindestens“ umfasst mehrere Werte.','Nutze das Gegenereignis oder addiere ab '+a+'.','Achte auf die Grenze.'));
 if(k===2)return C('Welche Aussage ist bei einer Stichprobe mit relativer Häufigkeit 0,7 korrekt?','0,7 ist eine Schätzung der unbekannten Trefferwahrscheinlichkeit p.',['p ist sicher genau 0,7.','In jeder nächsten Stichprobe treten 70 % Treffer auf.'],'Eine relative Häufigkeit liefert Information über p, aber Zufallsschwankung und Unsicherheit bleiben.',H('Stichprobe und Grundgesamtheit unterscheiden.','Eine Schätzung ist keine Gewissheit.','Neue Stichproben können abweichen.'),{rep:'kontextuell'});
 return C('„P(X=3)“ und „P(X≥3)“ unterscheiden sich. Was gilt?','P(X≥3) umfasst X=3,4,5,…; es ist mindestens so groß wie P(X=3).',['Beide sind immer gleich.','P(X≥3) umfasst nur X=3.'],'„Mindestens“ schließt den Grenzwert und alle größeren Werte ein.',H('Lies den Operator genau.','Liste die möglichen Trefferzahlen.','≥ bedeutet größer oder gleich.'));
};

G.normal=(k,d,r,v)=>{let mu=50,s=5;
 if(k===0)return N('X ist normalverteilt mit μ=50 und σ=5. Wie groß ist der z-Wert für x=60?',2,`z=(60−50)/5=2.`,H('Standardisieren: z=(x−μ)/σ.','Ziehe den Mittelwert ab.','Teile durch die Standardabweichung.'));
 if(k===1)return C('Was beschreibt die Fläche unter einer Dichtekurve zwischen a und b?','Die Wahrscheinlichkeit P(a≤X≤b).',['Die Dichte an einem einzelnen Punkt.','Die Standardabweichung.'],'Bei einer stetigen Zufallsgröße entspricht die Fläche unter der Dichte über einem Intervall der Intervallwahrscheinlichkeit.',H('Eine Dichtehöhe ist keine Wahrscheinlichkeit.','Wahrscheinlichkeiten entstehen durch Flächen.','Das Intervall legt die Grenzen fest.'));
 if(k===2)return N('Bei einer Normalverteilung liegen nach der 1σ-Regel ungefähr wie viel Prozent der Werte im Intervall [μ−σ; μ+σ]?',68.3,'Die 1σ-Regel liefert näherungsweise 68,3 %.',H('Es geht um ein zentrales symmetrisches Intervall.','Die 2σ-Regel wäre ungefähr 95,5 %.','Bei 1σ sind es rund 68 %.'));
 return C('Was bewirkt ein größeres σ bei gleichem μ?','Die Glocke wird breiter und flacher.',['Sie verschiebt sich nur nach rechts.','Die Gesamtfläche wird größer als 1.'],'Die Gesamtfläche bleibt 1; größere Streuung verteilt sie über ein breiteres Intervall.',H('σ misst Streuung.','μ bestimmt die Lage.','Wahrscheinlichkeiten bleiben insgesamt 1.'));
};

G.konfidenz=(k,d,r,v)=>{let a=r(90,98);
 if(k===0)return N(`Eine Stichprobe liefert p̂=0,${a}. Im Unterricht wird ein vereinfachtes 95%-Intervall p̂±0,04 verwendet. Gib die untere Grenze an.`,a/100-.04,`0,${a}−0,04=${fmt(a/100-.04,2)}.`,H('Ziehe die halbe Intervallbreite ab.','p̂ ist die Mitte des Intervalls.',`p̂=0,${a}.`),{tolerance:.001});
 if(k===1)return C('Was ist die korrekte Interpretation eines 95%-Konfidenzintervalls für p?','Das Verfahren erzeugt in vielen gleichartigen Stichproben Intervalle, die p ungefähr in 95 % der Fälle überdecken.',['Mit 95 % Wahrscheinlichkeit liegt p in genau diesem bereits berechneten Intervall.','95 % der Einzelwerte liegen im Intervall.'],'Die klassische Interpretation bezieht sich auf die Trefferquote des Verfahrens bei wiederholten Stichproben, nicht auf eine Zufallswahrscheinlichkeit des festen Parameters.',H('p ist ein fester, unbekannter Parameter.','Das Verfahren ist zufällig, p nicht.','Einzelwerte gehören zu Prognoseintervallen.'));
 if(k===2)return N('Warum wird ein Konfidenzintervall bei größerem Stichprobenumfang typischerweise enger?',1,`Die Standardfehler werden kleiner; dadurch sinkt die Unsicherheit der Schätzung.`,H('Mehr Daten liefern mehr Information.','Der Schätzfehler nimmt ungefähr mit 1/√n ab.','Die Intervallbreite wird nicht durch bloßes Runden kleiner.'));
 return C('Was muss bei der Planung eines Stichprobenumfangs neben der gewünschten Sicherheit berücksichtigt werden?','Die gewünschte Intervallbreite bzw. Fehlertoleranz.',['Nur die Farbe der Datenpunkte.','Nur der bisherige Mittelwert.'],'Sicherheit und Präzision bestimmen gemeinsam den nötigen Stichprobenumfang; kleinere Fehlertoleranz verlangt mehr Daten.',H('Ein enges Intervall ist präziser.','Präzision kostet Stichprobenumfang.','Sicherheit und Breite sind verschiedene Ziele.'));
};

G.abstand=(k,d,r,v)=>{let a=r(2,5);
 if(k===0)return N(`P(${a}|0|0), Q(0|0|0). Bestimme den Abstand PQ.`,a,`PQ=√(${a}²)=${a}.`,H('Der Abstand ist die Länge des Verbindungsvektors.','Nur eine Koordinate ändert sich.',`|${a}|=${a}.`));
 if(k===1)return C('Wie erhält man den Lotfußpunkt von P auf einer Ebene?','Schnittpunkt der Ebene mit der durch P gehenden Normalengeraden.',['Beliebiger Punkt der Ebene.','Schnittpunkt mit einer Parallelen zur Ebene.'],'Die kürzeste Verbindung steht senkrecht auf der Ebene und verläuft deshalb in Normalenrichtung.',H('Der kürzeste Weg ist senkrecht.','Eine Normale steht senkrecht auf der Ebene.','Der Lotfuß liegt zusätzlich in der Ebene.'));
 if(k===2)return N(`P(${a}|0|0) wird am Ursprung gespiegelt. Bestimme P′.`,[-a,0,0],`Der Ursprung ist Mittelpunkt: P′=(−${a}|0|0).`,H('Beim Spiegeln bleibt der Mittelpunkt der Strecke der Spiegelpunkt.','Der Abstand zum Ursprung bleibt gleich.','Das Vorzeichen der x-Koordinate wechselt.'),{labels:['x','y','z']});
 return C('Warum muss ein Normalenvektor für die Hesse-Normalform normiert werden?','Damit durch das Skalarprodukt direkt der senkrechte Abstand entsteht.',['Damit die Ebene größer wird.','Damit der Normalenvektor parallel zur Ebene liegt.'],'Nur ein Einheitsnormalenvektor misst die Projektion in Längeneinheiten.',H('Normieren heißt auf Länge 1 bringen.','Der Abstand ist eine Projektion.','Ein Faktor im Normalenvektor würde den Wert skalieren.'));
};
